# Generated by Django 2.2.16 on 2022-05-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_grouppost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPost',
        ),
    ]
